services:
  - type: web
    name: saini-txt-direct
    env: docker
    plan: free
    repo: https://github.com/qmnb12/saini-txt-direct
    branch: main
    autoDeploy: false
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER
        sync: false
      - key: CREDIT
        sync: false
      - key: PORT
        value: "8000"
